# Generated by Django 4.1 on 2022-12-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='busy_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
