# Generated by Django 4.1 on 2022-12-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'director'), (2, 'waiter'), (3, 'manager'), (4, 'cooker'), (5, 'call-center')], null=True),
        ),
    ]
