# Generated by Django 4.1.4 on 2022-12-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rooms_busy_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
