# Generated by Django 4.1.4 on 2022-12-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='busy_date',
        ),
    ]
