# Generated by Django 4.1.4 on 2022-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_user_img_remove_user_is_waiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='rooms',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
