# Generated by Django 4.1.2 on 2022-12-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_botdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
