# Generated by Django 4.1.4 on 2022-12-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_order_phone_rooms_busy_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='%m-%d-%Y'),
        ),
    ]
