# Generated by Django 4.1.2 on 2022-12-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_rooms_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
