# Generated by Django 4.1.4 on 2022-12-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_rooms_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
